export const HOME = '/home'
export const SIGN_UP = '/signup'
export const LOGIN = '/login'
export const LISTINGS = '/listing'
export const SEARCH = '/search'
export const EDIT = '/edit'
export const ALL_LISTINGS = '/alllistings'